name: promo

features:
  # @see https://docs.digitalocean.com/products/app-platform/how-to/upgrade-stack/
  - buildpack-stack=ubuntu-22
  # Opt in to the new Heroku Node.js buildpack if app is on the legacy one.
  #
  # @see https://docs.digitalocean.com/products/app-platform/how-to/migrate-nodejs-buildpack/
  - new-nodejs-buildpack=true

ingress:
  rules:
  - component:
      name: web
    match:
      path:
        prefix: /

static_sites:
- build_command: yarn build:production
  environment_slug: node-js
  gitlab:
    branch: main
    repo: neurocracy/promo
  index_document: index.htm
  name: web
  output_dir: web
  source_dir: /

envs:
  # Reusing Yarn cache on App Platform seems to not work as expected and results
  # in a failed build due to error:
  #
  # mv: cannot move '/layers/heroku_nodejs/shim/node/cache/yarn' to '/workspace/.yarn/cache': No such file or directory
- key: NODE_MODULES_CACHE
  scope: BUILD_TIME
  value: 'false'
- key: USE_YARN_CACHE
  scope: BUILD_TIME
  value: 'false'
